# Generated by Django 4.2.6 on 2023-10-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('suppliername', models.TextField()),
                ('contact', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
