# Generated by Django 4.2.6 on 2023-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_alter_category_name_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
